services:
  ingress:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      HTTPS_METHOD: nohttps
  student:
    build:
      context: student-service
      dockerfile: Dockerfile
    ports:
      - "8441:8443"
    external_links:
      - "mysql8:mysql8"
    environment:
      db_host: mysql8
      db_port: 3306
      db_user: student_service
      db_password: student_service
      db_name: student
      VIRTUAL_HOST: dev.local
      VIRTUAL_PATH: /student
  subject:
    build:
      context: subject-service
      dockerfile: jar.Dockerfile
    ports:
      - "8442:8443"
    external_links:
      - "mysql8:mysql8"
    environment:
      db_host: mysql8
      db_port: 3306
      db_user: subject_service
      db_password: subject_service
      VIRTUAL_HOST: dev.local
      VIRTUAL_PATH: /subject
  room:
    build:
      context: room-service
      dockerfile: jar.Dockerfile
    ports:
      - "8443:8080"
    external_links:
      - "mysql8:mysql8"
    environment:
      db_host: mysql8
      db_port: 3306
      db_user: room_service
      db_password: room_service
      VIRTUAL_HOST: dev.local
      VIRTUAL_PATH: /room
  courseplan:
    build:
      context: course-plan-service
      dockerfile: Dockerfile
    ports:
      - "8444:8443"
    external_links:
      - "mysql8:mysql8"
    links:
      - "room:room"
      - "student:student"
      - "subject:subject"
    environment:
      db_host: mysql8
      db_port: 3306
      db_user: course_plan_service
      db_password: course_plan_service
      student_api: student
      subject_api: subject
      schedule_api: room
      VIRTUAL_HOST: dev.local
      VIRTUAL_PATH: /courseplan
