server:
  port: 8080

datasource:
   jdbcUrl: jdbc:mysql://${db_host}:${db_port}/room
   driverClass: com.mysql.cj.jdbc.Driver
   username: ${db_user}
   password: ${db_password}

springdoc:
  api-docs:
    path: /room/api-doc