apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-service
  namespace: schl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-service
  template:
    metadata:
      labels:
        app: subject-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: mysql
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: mysql
            - name: DB_USER
              value: subject_service
            - name: DB_PASSWORD
              value: subject_service
          image: docker.local:5000/subject-service:latest
          imagePullPolicy: Always
          name: subject-service
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: subject-service
  namespace: schl
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: app-port
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: subject-service
  type: ClusterIP