micronaut:
    application:
        name: subject-service
    server:
        port: 8443

datasource:
    subject:
        jdbcUrl: jdbc:mysql://${db_host}:${db_port}/subject
        username: ${db_user}
        password: ${db_password}
        dialect: mysql
        driverClassName: com.mysql.cj.jdbc.Driver