apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-plan-service
  namespace: schl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-plan-service
  template:
    metadata:
      labels:
        app: course-plan-service
    spec:
      containers:
        - env:
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: mysql
            - name: db_port
              valueFrom:
                configMapKeyRef:
                  key: db_port
                  name: mysql
            - name: db_user
              value: course_plan_service
            - name: db_password
              value: course_plan_service
            - name: student_api
              valueFrom:
                configMapKeyRef:
                  key: student_api
                  name: api
            - name: subject_api
              valueFrom:
                configMapKeyRef:
                  key: subject_api
                  name: api
            - name: schedule_api
              valueFrom:
                configMapKeyRef:
                  key: schedule_api
                  name: api
          image: docker.local:5000/course-plan-service:latest
          imagePullPolicy: Always
          name: course-plan-service
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: course-plan-service
  namespace: schl
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: app-port
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: course-plan-service
  type: ClusterIP
